### ISSUE TITLE
Add Stable Diffusion v2 as a Collection

### ISSUE THREAD

**Issue by weberwcwei** [quic/wos-ai-plugins#1]
Hello, 

Could you add Stable Diffusion v2 as a collection? It offers significant improvements and would be a great addition.

Thanks!

**Comment by quic-prudhvi** [comment]
Hi @weberwcwei , 

Thanks for reaching out to us. We are planning to release SD 2.1 soon. (in 2 or 3 weeks).

**Comment by axcpy08** [comment]
Hello. How's SD 2.1 going? When can we expect to see it? Thanks!

**Comment by quic-prudhvi** [comment]
Kindly checkout the Automatic1111 plugin which contains 2.1 model.
