### ISSUE TITLE
Automatic1111 Instructions & Jobs

### ISSUE THREAD

**Issue by ncrispi** [quic/wos-ai-plugins#4]
I have followed the instructions to install the Automatic1111 UI, however, when I run a txt2img job via the UI, it is taking upwards of 20 minutes and does not appear to be using the ngpu per Task Manager. I am using a laptop with the Snapdragon X Elite processor... not sure if I am missing a step or doing something wrong

**Comment by ncrispi** [comment]
Reinstalled and it seems to be working fine and generating images in seconds now :)

**Comment by quic-prudhvi** [comment]
Great!. Good to know the issue is fixed.
