### ISSUE TITLE
[Installation instruction] small typo

### ISSUE THREAD

**Issue by BrickDesignerNL** [quic/wos-ai-plugins#5]
`install_plugin.ps1` instead of `install_plugin.bat`
in the v1.3 release: https://github.com/quic/wos-ai-plugins/releases/tag/v1.3-gimp

Also it might be nice to refer to the files below - for people less common with GitHub, for example:

> Download the `wos-ai-plugins-v1.3-gimp-arm64.zip` file listed below under Assets and unzip it and then double click on the `install_plugin.bat` file located in the extracted folder.

**Comment by quic-prudhvi** [comment]
@BrickDesignerNL , Thank you for raising this issue. I have made necessary changes.
